"""Build the PSČ -> kraj and obec -> kraj data files from real public datasets.

Primary source (exact PSČ + 3-digit prefix fallbacks, and municipality names):
    https://github.com/gunsoft/obce-okresy-kraje-slovenska
    (``CSV/villages.csv`` + ``CSV/regions.csv``) - 4208 Slovak municipalities
    with their PSČ and region. This dataset omits the Bratislava city PSČ
    (80xxx-85xxx), because Bratislava is a city, not a village.

Secondary source (Bratislava city coverage):
    GeoNames postal code export ``SK.zip``
    https://download.geonames.org/export/zip/SK.zip (CC BY 4.0), whose
    ``admin1`` column is the Slovak kraj. Every 8xx prefix present there maps
    to ``Bratislava`` only, which confirms those prefixes belong entirely to
    the Bratislavský kraj.
    The whole-city fallback code ``800 00`` is documented on
    https://sk.wikipedia.org/wiki/Poštové_smerovacie_čísla_na_Slovensku

Outputs (all regenerated by re-running this script):

* ``src/data/psc_kraje.csv`` - columns ``psc,kraj,confidence``
* ``src/data/psc_kraje_overrides.csv`` - columns
  ``psc,kraj,confidence,source``; loaded *after* the main file by ``geo.py``
  so it fills (and may correct) the gaps left by the primary source.
* ``src/data/obce_kraje.csv`` - columns ``obec,kraj,confidence``; normalized
  municipality name -> kraj for the city fallback. ``confidence`` is
  ``unique`` when the normalized name occurs in exactly one kraj, otherwise
  ``ambiguous`` (and then ``kraj`` holds the sorted candidate kraje joined by
  ``;`` and ``geo.py`` deliberately refuses to guess).
"""

from __future__ import annotations

import csv
import io
import pathlib
import sys
import zipfile
from collections import Counter, defaultdict
from urllib.request import Request, urlopen

_SRC = pathlib.Path(__file__).resolve().parent
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from text import normalize_text  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT_PATH = ROOT / "src" / "data" / "psc_kraje.csv"
OVERRIDES_PATH = ROOT / "src" / "data" / "psc_kraje_overrides.csv"
CITY_OUT_PATH = ROOT / "src" / "data" / "obce_kraje.csv"

RAW = "https://raw.githubusercontent.com/gunsoft/obce-okresy-kraje-slovenska/master/CSV/"
GEONAMES_URL = "https://download.geonames.org/export/zip/SK.zip"
USER_AGENT = "bazos-personal-monitor/0.1 (personal use)"

GEONAMES_SOURCE = (
    "GeoNames SK postal codes "
    "(https://download.geonames.org/export/zip/SK.zip), admin1=Bratislava"
)
WIKIPEDIA_SOURCE = (
    "Wikipedia: Poštové smerovacie čísla na Slovensku "
    "(https://sk.wikipedia.org/wiki/Poštové_smerovacie_čísla_na_Slovensku), 800 00 celomestské PSČ"
)

# GeoNames spells admin1 without diacritics; map to the Slovak kraj names used
# by the primary dataset and by the rest of the app.
GEONAMES_ADMIN1 = {
    "Bratislava": "Bratislavský kraj",
    "Banska Bystrica": "Banskobystrický kraj",
    "Kosice": "Košický kraj",
    "Nitra": "Nitriansky kraj",
    "Presov": "Prešovský kraj",
    "Trencin": "Trenčiansky kraj",
    "Trnava": "Trnavský kraj",
    "Zilina": "Žilinský kraj",
}


def _download(url: str) -> str:
    request = Request(url, headers={"User-Agent": USER_AGENT})
    with urlopen(request, timeout=60) as response:  # noqa: S310 - fixed https URL
        return response.read().decode("utf-8")


def _download_bytes(url: str) -> bytes:
    request = Request(url, headers={"User-Agent": USER_AGENT})
    with urlopen(request, timeout=60) as response:  # noqa: S310 - fixed https URL
        return response.read()


def _digits(value: str) -> str:
    return "".join(ch for ch in value if ch.isdigit())


def load_primary() -> tuple[dict[str, str], list[list[str]]]:
    """Return ``(regions, village_rows)`` from the gunsoft dataset."""
    regions = {
        row[0]: row[1]
        for row in csv.reader(_download(RAW + "regions.csv").splitlines())
        if len(row) >= 2
    }
    villages = list(csv.reader(_download(RAW + "villages.csv").splitlines()))
    return regions, villages


def build(regions: dict[str, str], villages: list[list[str]]) -> list[tuple[str, str, str]]:
    by_psc: dict[str, Counter] = defaultdict(Counter)
    for row in villages:
        if len(row) < 6:
            continue
        psc = _digits(row[3])
        region = regions.get(row[5])
        if len(psc) == 5 and region:
            by_psc[psc][region] += 1

    rows: list[tuple[str, str, str]] = []
    prefix_regions: dict[str, set[str]] = defaultdict(set)

    for psc in sorted(by_psc):
        counter = by_psc[psc]
        region, _ = counter.most_common(1)[0]
        confidence = "exact" if len(counter) == 1 else "uncertain"
        rows.append((psc, region, confidence))
        prefix_regions[psc[:3]].add(region)

    prefix_rows: list[tuple[str, str, str]] = []
    for prefix in sorted(prefix_regions):
        # Determine the prefix's region distribution across all its PSČ.
        distribution: Counter = Counter()
        for psc, counter in by_psc.items():
            if psc[:3] == prefix:
                distribution.update(counter)
        region, _ = distribution.most_common(1)[0]
        confidence = "prefix" if len(prefix_regions[prefix]) == 1 else "uncertain"
        prefix_rows.append((prefix, region, confidence))

    return rows + prefix_rows


def build_obce_kraje(regions: dict[str, str], villages: list[list[str]]) -> list[tuple[str, str, str]]:
    """Normalized municipality name -> kraj (``unique`` or ``ambiguous``)."""
    by_name: dict[str, Counter] = defaultdict(Counter)
    for row in villages:
        if len(row) < 6:
            continue
        region = regions.get(row[5])
        if not region:
            continue
        # row[1] is the full name, row[2] a short/ASCII variant used by the
        # source; index both as aliases.
        for name in {row[1], row[2]}:
            normalized = normalize_text(name)
            if normalized:
                by_name[normalized][region] += 1

    rows: list[tuple[str, str, str]] = []
    for name in sorted(by_name):
        counter = by_name[name]
        if len(counter) == 1:
            region, _ = counter.most_common(1)[0]
            rows.append((name, region, "unique"))
        else:
            rows.append((name, ";".join(sorted(counter)), "ambiguous"))
    return rows


def build_overrides() -> list[tuple[str, str, str, str]]:
    """Bratislava city prefixes from GeoNames, plus the 800 00 fallback code."""
    with zipfile.ZipFile(io.BytesIO(_download_bytes(GEONAMES_URL))) as archive:
        lines = archive.read("SK.txt").decode("utf-8").splitlines()

    by_prefix: dict[str, Counter] = defaultdict(Counter)
    for line in lines:
        parts = line.split("\t")
        if len(parts) < 5:
            continue
        psc = _digits(parts[1])
        region = GEONAMES_ADMIN1.get(parts[3])
        if len(psc) == 5 and region:
            by_prefix[psc[:3]][region] += 1

    rows: list[tuple[str, str, str, str]] = []
    for prefix in sorted(by_prefix):
        if not prefix.startswith("8"):
            continue
        counter = by_prefix[prefix]
        region, _ = counter.most_common(1)[0]
        confidence = "prefix" if len(counter) == 1 else "uncertain"
        rows.append((prefix, region, confidence, GEONAMES_SOURCE))

    # Whole-city fallback PSČ, documented by Wikipedia (not in GeoNames).
    rows.append(("80000", "Bratislavský kraj", "exact", WIKIPEDIA_SOURCE))
    return rows


def _write(path: pathlib.Path, header: list[str], rows: list[tuple]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(header)
        writer.writerows(rows)


def main() -> int:
    regions, villages = load_primary()

    rows = build(regions, villages)
    _write(OUT_PATH, ["psc", "kraj", "confidence"], rows)
    exact = sum(1 for r in rows if len(r[0]) == 5)
    prefix = sum(1 for r in rows if len(r[0]) == 3)
    print(f"Wrote {OUT_PATH.name}: {exact} exact PSČ rows, {prefix} prefix rows")

    overrides = build_overrides()
    _write(OVERRIDES_PATH, ["psc", "kraj", "confidence", "source"], overrides)
    bratislava = sum(1 for r in overrides if r[1] == "Bratislavský kraj")
    uncertain = sum(1 for r in overrides if r[2] == "uncertain")
    print(
        f"Wrote {OVERRIDES_PATH.name}: {len(overrides)} rows "
        f"({bratislava} Bratislavský kraj, {uncertain} uncertain)"
    )

    cities = build_obce_kraje(regions, villages)
    _write(CITY_OUT_PATH, ["obec", "kraj", "confidence"], cities)
    unique = sum(1 for r in cities if r[2] == "unique")
    ambiguous = sum(1 for r in cities if r[2] == "ambiguous")
    print(
        f"Wrote {CITY_OUT_PATH.name}: {len(cities)} normalized names "
        f"({unique} unique, {ambiguous} ambiguous)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
