"""Load the bazos.sk category catalog from ``categories.yaml`` (Phase 2).

The catalog is generated by ``src/build_categories.py`` from the homepage and
the category map. Each entry is a selectable category: a top-level section
(``parent_key is None``) or a subcategory of one.
"""

from __future__ import annotations

import functools
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import yaml

CATEGORIES_FILE = Path(__file__).resolve().parents[1] / "categories.yaml"


@dataclass(frozen=True)
class Category:
    key: str            # e.g. "pc" or "pc/notebook"
    label: str          # Slovak label, e.g. "PC" or "PC > Notebooky"
    host: str           # e.g. "pc.bazos.sk"
    path: str           # e.g. "/notebook/"
    parent_key: Optional[str]  # None for top-level sections
    url: str            # full base URL, e.g. "https://pc.bazos.sk/notebook/"


@functools.lru_cache(maxsize=8)
def _catalog(
    source_str: str, mtime: float
) -> tuple[tuple[Category, ...], dict[str, Category]]:
    """Parse the catalog once per (file, mtime); cached across calls."""
    data = yaml.safe_load(Path(source_str).read_text(encoding="utf-8")) or {}
    categories = tuple(Category(**entry) for entry in data.get("categories", []))
    return categories, {category.key: category for category in categories}


def _load(source: Optional[str | Path]):
    path = (Path(source) if source is not None else CATEGORIES_FILE).resolve()
    try:
        mtime = path.stat().st_mtime
    except OSError:
        mtime = 0.0
    return _catalog(str(path), mtime)


def load_categories(path: Optional[str | Path] = None) -> list[Category]:
    """Return every category in the catalog (sections first, then subcats)."""
    categories, _ = _load(path)
    return list(categories)


def get_category(key: str, path: Optional[str | Path] = None) -> Optional[Category]:
    """Return the category with ``key`` or ``None`` if it does not exist."""
    _, index = _load(path)
    return index.get(key)
