"""Location lookup: PSČ -> kraj and city -> kraj, plus classification.

Data comes from files generated by ``src/build_psc_kraje.py``:

* ``src/data/psc_kraje.csv`` - the main dataset
  https://github.com/gunsoft/obce-okresy-kraje-slovenska (4208 municipalities
  with PSČ and region);
* ``src/data/psc_kraje_overrides.csv`` - loaded *after* the main file and
  filling its gaps (the Bratislava city PSČ 80xxx-85xxx, which the primary
  source omits). Each row carries a ``source`` column;
* ``src/data/obce_kraje.csv`` - normalized municipality name -> kraj, used as
  a fallback when the PSČ does not yield a region. Ambiguous names (present
  in several kraje) are stored but never used.

Lookup order: exact 5-digit PSČ match, then longest-prefix match (4, then 3
digits). Returns ``None`` when nothing matches.
"""

from __future__ import annotations

import csv
import re
from functools import lru_cache
from pathlib import Path

from config import load_config
from text import normalize_text

DATA_DIR = Path(__file__).resolve().parent / "data"
CSV_PATH = DATA_DIR / "psc_kraje.csv"
OVERRIDES_PATH = DATA_DIR / "psc_kraje_overrides.csv"
CITY_CSV_PATH = DATA_DIR / "obce_kraje.csv"

# Sentinel used as the ``kraj`` filter value for "location unknown" rows.
KRAJ_UNKNOWN = "unknown"

# The three PSČ ranges assigned to Slovakia (0xx, 8xx, 9xx). A well-formed
# 5-digit code outside them is a known non-Slovak pattern (e.g. 11000 is a
# Czech PSČ).
SK_PSČ_FIRST_DIGITS = frozenset("089")

# Listings advertised abroad. The scraped data uses city "Zahraničie" with PSČ
# 12345 and city "Česká republika" with PSČ 11000; these are foreign listings,
# not merely an invalid/placeholder PSČ.
FOREIGN_CITIES = frozenset({"zahranicie", "ceska republika"})
FOREIGN_PSC = frozenset({"12345", "11000"})

# Abbreviations actually seen in the scraped city names, expanded before the
# municipality lookup. The DB contains e.g. "Nové Mesto n.Váhom" while the
# source dataset spells it "Nové Mesto nad Váhom"; the source itself also
# uses the "n/" form ("Bohdanovce n/Trnavou").
_CITY_ABBREVIATIONS = (
    (re.compile(r"\bn\.\s*"), "nad "),
    (re.compile(r"\bn/\s*"), "nad "),
)


def normalize_psc(psc: str | None) -> str:
    """Keep digits only (``"040 12"`` -> ``"04012"``)."""
    return re.sub(r"\D", "", psc or "")


def normalize_city(city: str | None) -> str:
    """Normalize a city name and expand known abbreviations."""
    text = normalize_text(city or "")
    for pattern, replacement in _CITY_ABBREVIATIONS:
        text = pattern.sub(replacement, text)
    return " ".join(text.split())


def _load(
    path: Path,
    exact: dict[str, tuple[str, str]],
    prefix: dict[str, tuple[str, str]],
) -> None:
    if not path.exists():
        return
    with path.open(encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            key = (row.get("psc") or "").strip()
            value = ((row.get("kraj") or "").strip(), (row.get("confidence") or "").strip())
            if len(key) == 5:
                exact[key] = value
            elif len(key) == 3:
                prefix[key] = value


@lru_cache(maxsize=1)
def _tables() -> tuple[dict[str, tuple[str, str]], dict[str, tuple[str, str]]]:
    exact: dict[str, tuple[str, str]] = {}
    prefix: dict[str, tuple[str, str]] = {}
    _load(CSV_PATH, exact, prefix)
    _load(OVERRIDES_PATH, exact, prefix)  # overrides win
    return exact, prefix


@lru_cache(maxsize=1)
def _city_table() -> dict[str, str]:
    """Normalized municipality name -> kraj, unique mappings only."""
    table: dict[str, str] = {}
    if not CITY_CSV_PATH.exists():
        return table
    with CITY_CSV_PATH.open(encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            if (row.get("confidence") or "").strip() != "unique":
                continue
            name = (row.get("obec") or "").strip()
            kraj = (row.get("kraj") or "").strip()
            if name and kraj:
                table[name] = kraj
    return table


@lru_cache(maxsize=1)
def _placeholder_psc() -> frozenset[str]:
    values = load_config().get("placeholder_psc") or []
    return frozenset(
        digits for digits in (normalize_psc(str(value)) for value in values) if digits
    )


def _lookup(psc: str | None) -> tuple[str, str] | None:
    digits = normalize_psc(psc)
    if len(digits) < 3:
        return None
    exact, prefix = _tables()
    if len(digits) == 5 and digits in exact:
        return exact[digits]
    for length in (4, 3):
        key = digits[:length]
        if key in prefix:
            return prefix[key]
    return None


def kraj_for_psc(psc: str | None) -> str | None:
    """Return the region name for a PSČ, or ``None``."""
    entry = _lookup(psc)
    return entry[0] if entry else None


def kraj_confidence(psc: str | None) -> str | None:
    """Return the confidence level for a PSČ match (``exact``/``prefix``/``uncertain``)."""
    entry = _lookup(psc)
    return entry[1] if entry else None


def kraj_for_city(city: str | None) -> str | None:
    """Return the region for a city name, only if it maps to exactly one kraj."""
    name = normalize_city(city)
    return _city_table().get(name) if name else None


def classify_location(
    psc: str | None,
    city: str | None,
    placeholders: frozenset[str] | None = None,
) -> tuple[str | None, str, str | None]:
    """Classify a listing location.

    Returns ``(kraj | None, psc_status, kraj_source)`` where

    * ``psc_status`` is ``valid`` (kraj found via PSČ), ``foreign`` (city is
      abroad, or the PSČ is a known foreign/placeholder value, or a well-formed
      non-Slovak PSČ), ``placeholder`` (PSČ in the configured placeholder list
      and not explained by a foreign city), ``unmatched`` (well-formed SK PSČ
      not in the dataset) or ``missing`` (empty PSČ);
    * ``kraj_source`` is ``psc``, ``city`` or ``None``.

    The city fallback is only tried when the PSČ did not yield a region, and
    only when the normalized city maps to exactly one kraj.
    """
    digits = normalize_psc(psc)
    if placeholders is None:
        placeholders = _placeholder_psc()
    city_name = normalize_city(city) if city else ""

    if not digits:
        status = "missing"
    elif city_name in FOREIGN_CITIES or digits in FOREIGN_PSC:
        # Listings advertised abroad ("Zahraničie" / "Česká republika") are
        # foreign, not merely an invalid PSČ.
        status = "foreign"
    elif digits in placeholders:
        status = "placeholder"
    elif len(digits) == 5 and digits[0] not in SK_PSČ_FIRST_DIGITS:
        status = "foreign"
    else:
        kraj = kraj_for_psc(digits)
        if kraj:
            return kraj, "valid", "psc"
        status = "unmatched"

    city_kraj = kraj_for_city(city) if city else None
    if city_kraj:
        return city_kraj, status, "city"
    return None, status, None


def all_kraje() -> list[str]:
    """The 8 Slovak region names, derived from the data file."""
    exact, prefix = _tables()
    return sorted({kraj for kraj, _ in list(exact.values()) + list(prefix.values())})
